/*
  fr-FR.h - localization for French - France for Sonoff-Tasmota

  Copyright (C) 2017  Theo Arends

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef _LANGUAGE_FR_FR_H_
#define _LANGUAGE_FR_FR_H_

/*************************** ATTENTION *******************************\
 *
 * Due to memory constraints only UTF-8 is supported.
 * To save code space keep text as short as possible.
 * Time and Date provided by SDK can not be localized (yet).
 * Use online command StateText to translate ON, OFF, HOLD and TOGGLE.
 * Use online command Prefix to translate cmnd, stat and tele.
 *
\*********************************************************************/

// "2017-03-07T11:08:02" - ISO8601:2004
#define D_YEAR_MONTH_SEPARATOR "/"
#define D_MONTH_DAY_SEPARATOR "/"
#define D_DATE_TIME_SEPARATOR "T"
#define D_HOUR_MINUTE_SEPARATOR ":"
#define D_MINUTE_SECOND_SEPARATOR ":"

#define D_DAY3LIST "DimLunMarMerJeuVenSam"
#define D_ALLDAY "Tous" // add cpat
#define D_MONTH3LIST "JanFevMarAvrMaiJuiJulAuoSepOctNovDec"

// Non JSON decimal separator
#define D_DECIMAL_SEPARATOR "."

// Common
#define D_ABORTED "Annule"
#define D_ACTIVE "Active"
#define D_ADDRESS "Adresse"
#define D_ADMIN "Admin"
#define D_AIR_QUALITY "Qual.Air"
#define D_AIRQUALITY "Qual.Air"
#define D_AP "AP"                    // Access Point
#define D_APMAC_ADDRESS "APMac"
#define D_APPENDED "Ajoute"
#define D_AS "Comme"
#define D_AUTO "AUTO"
#define D_BAUDRATE "Baudrate"
#define D_BLINK "Clign."
#define D_BLINKOFF "Off Clign."
#define D_BOOTVERSION "Demarrage"
#define D_BOOT_COUNT "Nb Demar."
#define D_BOOTCOUNT "Nb Cycle"
#define D_BRIGHTLIGHT "Max."
#define D_BUILDDATETIME "Temps Allum."
#define D_BUTTON "Bouton"
#define D_CELSIUS "Celsius"
#define D_CODE "code"                // Button code
#define D_COLDLIGHT "Blanc Froid"
#define D_COMMAND "Commande"
#define D_CONNECTED "Connecte"
#define D_COREVERSION "Brut"
#define D_COUNT "Compte"
#define D_COUNTER "Compteur"
#define D_CURRENT "Intensite"          // As in Voltage and Current
#define D_DATA "Donnee"
#define D_DARKLIGHT "Min."
#define D_DEBUG "M.au P."
#define D_DISABLED "Desactive"
#define D_DNS_SERVER "DNS Serveur"
#define D_DNSSERVER "DNSServeur"
#define D_DONE "Fait"
#define D_DST_TIME "H.Ete"
#define D_EMPTY "Vide"
#define D_EMULATION "Emulation"
#define D_ENABLED "Active"
#define D_ENDDST "Fin H.Ete"           // End Daylight Savings Time
#define D_ERASE "Efface"
#define D_ERROR "Erreur"
#define D_EVERY "Chaque"
#define D_FAHRENHEIT "Fahrenheit"
#define D_FAILED "Echoue"
#define D_FALLBACK "Secours"
#define D_FALLBACK_TOPIC "Sujet Sec."
#define D_FALLBACKTOPIC "Suj.Sec."
#define D_FALSE "Faux"
#define D_FILE "Fichier"
#define D_FLASHMODE "Mode Charg."
#define D_FLASHSIZE "Taille Charg."
#define D_FREE_MEMORY "M&#233m.Libre"
#define D_FREEMEMORY "Libre"
#define D_FROM "Depuis"
#define D_GATEWAY "Passerelle"
#define D_GROUP "Groupe"
#define D_HEAPSIZE "Entasse"
#define D_HIGH "Haut"
#define D_HOST "Hote"
#define D_HOSTNAME "Nom hote"
#define D_HUMIDITY "Humidite"
#define D_ILLUMINANCE "Eclairement"
#define D_IMMEDIATE "immediat"      // Button immediate
#define D_INDEX "Index"
#define D_INFO "Info"
#define D_INITIALIZED "Initialise"
#define D_IP_ADDRESS "Adr.IP"
#define D_LIGHT "Allume"
#define D_LOCAL_TIME "Locale"
#define D_LOW "Bas"
#define D_LWT "LWT"
#define D_MAC "Mac"
#define D_MASK "Masque"
#define D_MODULE "Mat."
#define D_MQTT "MQTT"
#define D_MULTI_PRESS "Mult.Ap."
#define D_NO "Non"
#define D_NOISE "Bruit"
#define D_NONE "Aucun"
#define D_OFF "Eteint"
#define D_OFFLINE "Hors Lig."
#define D_OK "Ok"
#define D_ON "On"
#define D_ONLINE "En Ligne"
#define D_OR "ou"
#define D_PASSWORD "Mot passe"
#define D_PERIOD "Periode"
#define D_PORT "Port"
#define D_POWER_FACTOR "Fact.Puissance"
#define D_POWERFACTOR "Facteur"
#define D_POWERUSAGE "Puissance"
#define D_PRESSURE "Pression"
#define D_PRESSUREATSEALEVEL "Pres.Niv.mer"
#define D_PROGRAM_FLASH_SIZE "Tail.Mem.Prog."
#define D_PROGRAMFLASHSIZE "Tail.MemProg"
#define D_PROGRAM_SIZE "Tail.Prog."
#define D_PROGRAMSIZE "Tail.Prog"
#define D_PROJECT "Projet"
#define D_RECEIVED "Recu"
#define D_RESTART "Redemar."
#define D_RESTARTING "Redemar."
#define D_RESTART_REASON "Raison Redem."
#define D_RESTARTREASON "CauseRedem."
#define D_RESTORE "restauration"
#define D_RETAINED "retenu"
#define D_SAVE "Sauve"
#define D_SAVEADDRESS "Adres.Sauvegarde"
#define D_SAVECOUNT "Nb Sauveg."
#define D_SAVESTATE "Etat Sauveg."
#define D_SDKVERSION "SDK"
#define D_SELECTED "selection"
#define D_SENSOR "Senseur"
#define D_SERIAL "S&#233rie"
#define D_BYTES "Bytes"
#define D_SSID "SSId"
#define D_START "Demarrage"
#define D_STARTED "Demarre"
#define D_STARTDST "H.Demarrage"        // Start Daylight Savings Time
#define D_STD_TIME "STD"
#define D_STOP "Stop"
#define D_SUBNET_MASK "Masque S.r&#233seau"
#define D_SUBNETMASK "MasqSousRes"
#define D_SUBSCRIBE_TO "s'abonner"
#define D_SUCCESSFUL "reussi"
#define D_SWITCH "Bascule"
#define D_SYNC "Synch"
#define D_SYS "Sys"                  // Sys log
#define D_TEMPERATURE "Temper."
#define D_TEMPERATURE_UNIT "UnitTemp"
#define D_TIME "Temps"
#define D_TO "A"
#define D_TODAY "Aujourd'hui"
#define D_TOGGLE "Inverser"
#define D_TOPIC "Sujet"
#define D_TOTAL "Total"
#define D_TRANSMIT "Transmis"
#define D_TRUE "Vrai"
#define D_TYPE "Type"
#define D_UNKNOWN "Inconnu"
#define D_UPGRADE "M.&#224 Niv."
#define D_UPLOAD "Charg&#233"
#define D_UPTIME "Temps Fonct."
#define D_USER "Utilis."
#define D_UTC_TIME "UTC"
#define D_UV_LEVEL "UV Level"
#define D_VCC "Vcc"
#define D_VERSION "Version"
#define D_VOLTAGE "Tension"
#define D_WARMLIGHT "Blanc Chaud"
#define D_WEB "Web"                  // Web log
#define D_WEB_SERVER "Serveur Web"
#define D_WIFI "Wifi"
#define D_WRONG "Faux"
#define D_YESTERDAY "Hier"

// settings.ino
#define D_SAVED_TO_FLASH_AT "Sauve Mem.le "
#define D_LOADED_FROM_FLASH_AT "Charge Mem. le"
#define D_USE_DEFAULTS "Valeurs Defaut"
#define D_ERASED_SECTOR "Secteur Efface"

// sonoff.ino
#define D_LEVEL_10 "Niveau 1-0"
#define D_LEVEL_01 "Niveau 0-1"
#define D_SERIAL_LOGGING_DISABLED "Journ.Serie Off"
#define D_SYSLOG_LOGGING_REENABLED "Journ.Serie On"

#define D_SET_BAUDRATE_TO "Baudrate a"
#define D_RECEIVED_TOPIC "Sujet Recu"
#define D_DATA_SIZE "Tail.Don."
#define D_ANALOG_INPUT "Analog."
#ifdef USE_ADC_MAX
	#define D_ADCCURRENTVALUE "Intensite" // add cpat
#endif
#ifdef USE_MQTT_TLS
	#define D_FINGERPRINT "Verif.TLS certif."
	#define D_TLS_CONNECT_FAILED_TO "Connect.Secur.non etablie"
	#define D_INSECURE "Connect.non securisee due mauvais certif."
#endif
	#define D_RETRY_IN "Recommence avec"
	#define D_VERIFIED "Verifie"
    #define D_CONNECT_FAILED_TO "Connect.non valide a"
// support.ino
#define D_OSWATCH "osWatch"
#define D_BLOCKED_LOOP "Boucle Verrouil."
#define D_WPS_FAILED_WITH_STATUS "WPSconfig echouee,status"
#define D_ACTIVE_FOR_1_MINUTE "active pour 1 min."
#define D_FAILED_TO_START "Echoue a demarrer"
#define D_PATCH_ISSUE_2186 "Resulat Patch 2186"
#define D_CONNECTING_TO_AP "Connect.au P.A."
#define D_IN_MODE "mode"
#define D_CONNECT_FAILED_NO_IP_ADDRESS "Connect.Echoue,pas d'IP address recue"
#define D_CONNECT_FAILED_AP_NOT_REACHED "Connect.Echoue,P.A. non trouve"
#define D_CONNECT_FAILED_WRONG_PASSWORD "Connect.Echoue,mauvais M.de P."
#define D_CONNECT_FAILED_AP_TIMEOUT "Connect.Echoue,P.A. timeout"
#define D_ATTEMPTING_CONNECTION "Tentat.connect..."
#define D_CHECKING_CONNECTION "Verif.connect..."
#define D_QUERY_DONE "Requete Ok.MQTT trouve"
#define D_MQTT_SERVICE_FOUND "Serv.MQTT trouve sur"
#define D_I2CSCAN_DEVICES_FOUND_AT "Materiel trouve a"
#define D_FOUND_AT "trouve a"
#define D_I2CSCAN_UNKNOWN_ERROR_AT "Erreur inconnue lors"
#define D_I2CSCAN_NO_DEVICES_FOUND "aucun mat.trouve"
#define D_SYSLOG_HOST_NOT_FOUND "Hote Syslog pas trouve"

// webserver.ino
#define D_MINIMAL_FIRMWARE_PLEASE_UPGRADE "Firmware Mini-SVP M&#224 niv."
#define D_WEBSERVER_ACTIVE_ON "Serv.Web on"
#define D_WITH_IP_ADDRESS "avec IP"
#define D_WEBSERVER_STOPPED "Serv.Web off"
#define D_FILE_NOT_FOUND "Fich.non trouve"
#define D_REDIRECTED "Redirig&#233 portail captif"
#define D_WIFIMANAGER_SET_ACCESSPOINT_AND_STATION "Wifimanager passe en PA/STA"
#define D_WIFIMANAGER_SET_ACCESSPOINT "Wifimanager en PA"
#define D_TRYING_TO_CONNECT "Essais connect.mat.r&#233seau"

#define D_RESTART_IN "Redemarre dans"
#define D_SECONDS "s"
#define D_DEVICE_WILL_RESTART "Mat.redemarrera dans qcq sec."
#define D_BUTTON_TOGGLE "On/Off"
#define D_BUTTON_UP "Haut" // use with dual r2 add cpat
#define D_BUTTON_DOWN "Bas"
#define D_CONFIGURATION "Configurations"
#define D_INFORMATION "Infos"
#define D_FIRMWARE_UPGRADE "M.&#224 J. Prog. ({dt)"
#define D_CONSOLE "Console"
#define D_CONFIRM_RESTART "Confirmer Red&#233marrage"

#define D_CONFIGURE_MODULE "Config.Mat&#233riel"
#define D_CONFIGURE_WIFI "Config.WiFi"
#define D_CONFIGURE_MQTT "Config.MQTT"
#define D_CONFIGURE_DOMOTICZ "Config.Domoticz"
#define D_CONFIGURE_LOGGING "Config.Journaux"
#define D_CONFIGURE_OTHER "Autres Config."
#define D_CONFIGURE_RELAY "Config.Relais"
#define D_CONFIRM_RESET_CONFIGURATION "Confirmer RAZ config."
#define D_RESET_CONFIGURATION "R.a Z. Config."
#define D_BACKUP_CONFIGURATION "Sauver Config."
#define D_RESTORE_CONFIGURATION "Restaure Config."
#define D_MAIN_MENU "Menu Principal"

#define D_MODULE_PARAMETERS "param&#232tres Mat&#233riel"
#define D_MODULE_TYPE "Type Mat." 
#define D_GPIO "GPIO"
#define D_SERIAL_IN "S&#233rie In RX"
#define D_SERIAL_OUT "S&#233rie Out TX"

#define D_WIFI_PARAMETERS "param&#232tres Wifi"
#define D_SCAN_FOR_WIFI_NETWORKS "D&#233tecter Wifi"
#define D_SCAN_DONE "D&#233tect.R&#233alis&#233e"
#define D_NO_NETWORKS_FOUND "Pas r&#233seau trouv&#233"
#define D_REFRESH_TO_SCAN_AGAIN "Relancer la d&#233tection"
#define D_DUPLICATE_ACCESSPOINT "Dupliquer P.A."
#define D_SKIPPING_LOW_QUALITY "Lattence due &#224 la liaison"
#define D_RSSI "RSSI"
#define D_WEP "WEP"
#define D_WPA_PSK "WPA PSK"
#define D_WPA2_PSK "WPA2 PSK"
#define D_AP1_SSID "SSId P.A.1"
#define D_AP1_PASSWORD "M.de P. P.A.1"
#define D_AP2_SSID "SSId P.A.2"
#define D_AP2_PASSWORD "M.de P. P.A.2"

#define D_MQTT_PARAMETERS "param&#232tres MQTT"
#define D_CLIENT "Client"
#define D_FULL_TOPIC "Sujet Complet"

#define D_LOGGING_PARAMETERS "param&#232tres Journaux"
#define D_LOG_LEVEL "Niveau"
#define D_MORE_DEBUG "Plus en Debug"
#define D_SYSLOG_HOST "Hote Syslog"
#define D_SYSLOG_PORT "Port Syslog"
#define D_TELEMETRY_PERIOD "Periode d'Envoi"

#define D_OTHER_PARAMETERS "Autres param&#232tres"
#define D_WEB_ADMIN_PASSWORD "M.de P. Admin Web"
#define D_MQTT_ENABLE "MQTT activ&#233"
#define D_FRIENDLY_NAME "Nom Mat&#233riel"
#define D_BELKIN_WEMO "Belkin WeMo"
#define D_HUE_BRIDGE "Hue Bridge"
#define D_SINGLE_DEVICE "single device"
#define D_MULTI_DEVICE "multi device"

#define D_SAVE_CONFIGURATION "Sauver config."
#define D_CONFIGURATION_SAVED "Config. sauv&#233e"
#define D_CONFIGURATION_RESET "Config. R.A Z."

#define D_PROGRAM_VERSION "Version Prog."
#define D_BUILD_DATE_AND_TIME "Date/Hrs Prog."
#define D_CORE_AND_SDK_VERSION "Core/SDK Version"
#define D_FLASH_WRITE_COUNT "Nb Ecrit.M&#233m."
#define D_MAC_ADDRESS "Adresse MAC"
#define D_MQTT_HOST "Hote MQTT"
#define D_MQTT_PORT "Port MQTT"
#define D_MQTT_CLIENT "Client MQTT"
#define D_MQTT_USER "Utilisat. MQTT"
#define D_MQTT_TOPIC "Sujet MQTT"
#define D_MQTT_GROUP_TOPIC "Groupe Sujet MQTT"
#define D_MQTT_FULL_TOPIC "Sujet Complet MQTT"
#define D_MDNS_DISCOVERY "D&#233couverte mDNS"
#define D_MDNS_ADVERTISE "Avertissem.mDNS"
#define D_ESP_CHIP_ID "n&deg Puce ESP"
#define D_FLASH_CHIP_ID "n&deg Puce M&#233m."
#define D_FLASH_CHIP_SIZE "Taille M&#233m."
#define D_FREE_PROGRAM_SPACE "Taille Prog. Libre"

#define D_UPGRADE_BY_WEBSERVER "Maj via Web serv."
#define D_OTA_URL "OTA Url"
#define D_START_UPGRADE "Lancer MaJ"
#define D_UPGRADE_BY_FILE_UPLOAD "Maj par fichier"
#define D_UPLOAD_STARTED "Chargem. demarr&#233"
#define D_UPGRADE_STARTED "MaJ demarr&#233e"
#define D_UPLOAD_DONE "Chargement Fait"
#define D_UPLOAD_ERR_1 "Pas de fichier fourni"
#define D_UPLOAD_ERR_2 "Pas assez d'espace"
#define D_UPLOAD_ERR_3 "byte magique <> 0xE9"
#define D_UPLOAD_ERR_4 "Taille Prog. > taille m&#233m."
#define D_UPLOAD_ERR_5 "Erreur V&#233rif.fichier "
#define D_UPLOAD_ERR_6 "D&#233faillance T&#233l&#233charg.,activer journ.n&deg 3"
#define D_UPLOAD_ERR_7 "T&#233l&#233charg. Annul&#233"
#define D_UPLOAD_ERR_8 "Fichier Invalide"
#define D_UPLOAD_ERR_9 "Fichier trop gros"
#define D_UPLOAD_ERROR_CODE "Erreur code t&#233l&#233charg."

#define D_ENTER_COMMAND "Entrer une commande"
#define D_ENABLE_WEBLOG_FOR_RESPONSE "Activez journ.web 2 pour r&#233ponse"
#define D_NEED_USER_AND_PASSWORD "besoin:user=<username>&password=<password>"

// add cpat menu web relai
#define D_RELAY_PARAMETERS "Param&#232tres Relais"
#define D_RELAY_NAME "Relais"
#define D_INTERLOCK_TITLE "Tous relais"
#define D_INTERLOCK_NO "Ind&#233;pendant"
#define D_INTERLOCK_YES "1 Seul &#224 la fois"
#define D_INTERLOCK_TIME "Delai Off (ms)"
//#define D_PULSETIMER_TITLE "Temps Auto Off (h:m:s)"
#define D_PULSETIMER_OF "Manuel"
#define D_PULSETIMER_OFF "T&#233;l&#233;rupteur"
#define D_PULSETIMER_ON "Minuterie"
#define D_TIMER_ON "Horloge"
#define D_TIME_ON "Heure On (J.h:m)"
#define D_TIME_OFF "Heure Off (h:m:s/J.h:m)"
#define D_SEND_OFF "Message Web Off"
#define D_SENDOFFURL "Adresse Message Off"
//#define D_TIMER_FORMAT "j/h:m"
#define D_TIMER_DAY "J:0 a 8"
// add cpat menu web relay

// xdrv_domoticz.ino
#define D_DOMOTICZ_PARAMETERS "param&#232tres Domoticz"
#define D_DOMOTICZ_IDX "Idx"
#define D_DOMOTICZ_KEY_IDX "Key idx"
#define D_DOMOTICZ_SWITCH_IDX "Switch idx"
#define D_DOMOTICZ_SENSOR_IDX "Sensor idx"
  #define D_DOMOTICZ_TEMP "Temp"
  #define D_DOMOTICZ_TEMP_HUM "Temp,Hum"
  #define D_DOMOTICZ_TEMP_HUM_BARO "Temp,Hum,Baro"
  #define D_DOMOTICZ_POWER_ENERGY "Puissance,Energy"
  #define D_DOMOTICZ_ILLUMINANCE "Eclairement"
  #define D_DOMOTICZ_COUNT "Compte"
  #define D_DOMOTICZ_VOLTAGE "Tension"
  #define D_DOMOTICZ_CURRENT "Courant"
#define D_DOMOTICZ_UPDATE_TIMER "Tempo.M.&#224 J."

// xdrv_ir-send.ino
#define D_INVALID_JSON "Invalid JSON"
#define D_PROTOCOL_NOT_SUPPORTED "Protocole non support&#233"
#define D_IR_PROTOCOL "PROTOCOL"
#define D_IR_BITS "BITS"
#define D_IR_DATA "DATA"
#define D_IRHVAC_VENDOR "VENDOR"
#define D_IRHVAC_POWER "POWER"
#define D_IRHVAC_MODE "MODE"
#define D_IRHVAC_FANSPEED "FANSPEED"
#define D_IRHVAC_TEMP "TEMP"
#define D_IRRECEIVED "IrReceived"

// xdrv_snfbridge.ino
#define D_RFRECEIVED "RfReceived"
#define D_START_LEARNING "Start learning"
#define D_SET_TO_DEFAULT "Set to default"
#define D_DEFAULT_SENT "Default sent"
#define D_LEARNED_SENT "Learned sent"
#define D_LEARNING_ACTIVE "Learning active"
#define D_LEARN_FAILED "Learn failed"
#define D_LEARNED "Learned"
#define D_SAVED "Saved"

// xdrv_wemohue.ino
#define D_MULTICAST_DISABLED "Multicast disabled"
#define D_MULTICAST_REJOINED "Multicast (re)joined"
#define D_MULTICAST_JOIN_FAILED "Multicast join failed"
#define D_FAILED_TO_SEND_RESPONSE "Failed to send response"

#define D_WEMO "WeMo"
#define D_WEMO_BASIC_EVENT "WeMo basic event"
#define D_WEMO_EVENT_SERVICE "WeMo event service"
#define D_WEMO_SETUP "WeMo setup"
#define D_RESPONSE_SENT "Response sent"

#define D_HUE "Hue"
#define D_HUE_BRIDGE_SETUP "Hue setup"
#define D_HUE_API_NOT_IMPLEMENTED "Hue API not implemented"
#define D_HUE_API "Hue API"
#define D_HUE_POST_ARGS "Hue POST args"
#define D_3_RESPONSE_PACKETS_SENT "3 Ret.packets sent"

// xsns_dht.ino
#define D_TIMEOUT_WAITING_FOR "Timeout waiting for"
#define D_START_SIGNAL_LOW "start signal low"
#define D_START_SIGNAL_HIGH "start signal high"
#define D_PULSE "pulse"
#define D_CHECKSUM_FAILURE "Checksum failure"

// xsns_ds18b20.ino
#define D_SENSOR_BUSY "Sensor busy"
#define D_SENSOR_CRC_ERROR "Sensor CRC error"

// xsns_hlw8012.ino
#ifdef Use_HLW8012
	#define D_MAXPOWERREACHED "MaxPowerReached"
	#define D_MAXPOWERREACHEDRETRY "MaxPowerReachedRetry"
	#define D_POWERMONITOR "PowerMonitor"
	#define D_ENERGYMONITOR "EnergyMonitor"
	#define D_MAXENERGYREACHED "MaxEnergyReached"
	#define D_ENERGY_TODAY "Energy Today"
	#define D_ENERGY_YESTERDAY "Energy Yesterday"
	#define D_ENERGY_TOTAL "Energy Total"
#endif
// xsns_sht1x.ino
#define D_SENSOR_DID_NOT_ACK_COMMAND "Sensor didn't ACK command"
#define D_SHT1X_FOUND "SHT1X found"

// sonoff_template.h
// Max string length is 8 characters including suffixes
#define D_SENSOR_NONE     "None"
#define D_SENSOR_DHT11    "DHT11"
#define D_SENSOR_AM2301   "AM2301"
#define D_SENSOR_DHT22    "DHT22"
#define D_SENSOR_DS18X20  "DS18x20"
#define D_SENSOR_I2C_SCL  "I2C SCL"
#define D_SENSOR_I2C_SDA  "I2C SDA"
#define D_SENSOR_WS2812   "WS2812"
#define D_SENSOR_IRSEND   "IRsend"
#define D_SENSOR_SWITCH   "Switch"   // Suffix "1"
#define D_SENSOR_BUTTON   "Button"   // Suffix "1"
#define D_SENSOR_RELAY    "Relay"    // Suffix "1i"
#define D_SENSOR_LED      "Led"      // Suffix "1i"
#define D_SENSOR_PWM      "PWM"      // Suffix "1"
#define D_SENSOR_COUNTER  "Counter"  // Suffix "1"
#define D_SENSOR_IRRECV   "IRrecv"
#define D_SENSOR_SPI_CS   "SPI CS"
#define D_SENSOR_SPI_DC   "SPI DC"
#define D_SENSOR_BACKLIGHT "BLight"

// Units
#define D_UNIT_AMPERE "A"
#define D_UNIT_HOUR "Hr"
#define D_UNIT_KILOWATTHOUR "kWh"
#define D_UNIT_LUX "lx"
#define D_UNIT_MICROSECOND "us"
#define D_UNIT_MILLIAMPERE "mA"
#define D_UNIT_MILLISECOND "ms"
#define D_UNIT_MINUTE "Min"
#define D_UNIT_PRESSURE "hPa"
#define D_UNIT_SECOND "sec"
#define D_UNIT_SECTORS "sectors"
#define D_UNIT_VOLT "V"
#define D_UNIT_WATT "W"
#define D_UNIT_WATTHOUR "Wh"

// Log message prefix
#define D_LOG_APPLICATION "APP: "
#define D_LOG_BRIDGE "BRG: "
#define D_LOG_CONFIG "CFG: "
#define D_LOG_COMMAND "CMD: "
#define D_LOG_DHT "DHT: "
#define D_LOG_DOMOTICZ "DOM: "
#define D_LOG_DSB "DSB: "
#define D_LOG_HTTP "HTP: "
#define D_LOG_I2C "I2C: "
#define D_LOG_IRR "IRR: "
#define D_LOG_LOG "LOG: "
#define D_LOG_MODULE "MOD: "
#define D_LOG_MDNS "DNS: "
#define D_LOG_MQTT "MQT: "
#define D_LOG_OTHER "OTH: "
#define D_LOG_RESULT "RSL: "
#define D_LOG_SERIAL "SER: "
#define D_LOG_SHT1 "SHT: "
#define D_LOG_UPLOAD "UPL: "
#define D_LOG_UPNP "UPP: "
#define D_LOG_WIFI "WIF: "

// Result
#define D_RSLT_RESULT "RESULT"
#define D_RSLT_INFO "INFO"
#define D_RSLT_STATE "STATE"
#define D_RSLT_SENSOR "SENSOR"
#define D_RSLT_UPTIME "UPTIME"
#define D_RSLT_MARGINS "MARGINS"
#define D_RSLT_WARNING "WARNING"
#define D_RSLT_ENERGY "ENERGY"

// Commands
#define D_CMND_MQTTHOST "MqttHost"
#define D_CMND_MQTTPORT "MqttPort"
#define D_CMND_MQTTRETRY "MqttRetry"
#define D_CMND_STATETEXT "StateText"
#define D_CMND_MQTTFINGERPRINT "MqttFingerprint"
#define D_CMND_MQTTCLIENT "MqttClient"
#define D_CMND_MQTTUSER "MqttUser"
#define D_CMND_MQTTPASSWORD "MqttPassword"
#define D_CMND_FULLTOPIC "FullTopic"
#define D_CMND_PREFIX "Prefix"
  #define PRFX_MAX_STRING_LENGTH 5
  #define D_CMND "cmnd"
  #define D_STAT "stat"
  #define D_TELE "tele"
#define D_CMND_GROUPTOPIC "GroupTopic"
#define D_CMND_TOPIC "Topic"
#define D_CMND_BUTTONTOPIC "ButtonTopic"
#define D_CMND_SWITCHTOPIC "SwitchTopic"
#define D_CMND_BUTTONRETAIN "ButtonRetain"
#define D_CMND_SWITCHRETAIN "SwitchRetain"
#define D_CMND_POWERRETAIN "PowerRetain"
#define D_CMND_SENSORRETAIN "SensorRetain"
#define D_CMND_BACKLOG "Backlog"
#define D_CMND_DELAY "Delay"
#define D_CMND_STATUS "Status"
  #define D_STATUS1_PARAMETER "PRM"
  #define D_STATUS2_FIRMWARE "FWR"
  #define D_STATUS3_LOGGING "LOG"
  #define D_STATUS4_MEMORY "MEM"
  #define D_STATUS5_NETWORK "NET"
  #define D_STATUS6_MQTT "MQT"
  #define D_STATUS7_TIME "TIM"
  #define D_STATUS8_POWER "PWR"
  #define D_STATUS9_MARGIN "PTH"
  #define D_STATUS10_SENSOR "SNS"
  #define D_STATUS11_STATUS "STS"
#define D_CMND_POWER "Power"
  #define D_RSLT_POWER "POWER"
#define D_CMND_POWERONSTATE "PowerOnState"
#define D_CMND_PULSETIME "PulseTime"
#define D_CMND_BLINKTIME "BlinkTime"
#define D_CMND_BLINKCOUNT "BlinkCount"
#define D_CMND_SAVEDATA "SaveData"
#define D_CMND_SETOPTION "SetOption"
#define D_CMND_TEMPERATURE_RESOLUTION "TempRes"
#ifndef USE_ADC_MAX // add cpat
	#define D_CMND_HUMIDITY_RESOLUTION "HumRes"
	#define D_CMND_PRESSURE_RESOLUTION "PressRes"
#else
	#define D_CMND_HUMIDITY_RESOLUTION "CurrMax"// i_max setting add cpat current Resolution
	#define D_CMND_PRESSURE_RESOLUTION "CurrRes" // WS_red settins add cpat current coef/10 
#endif
#define D_CMND_POWER_RESOLUTION "WattRes"
#define D_CMND_VOLTAGE_RESOLUTION "VoltRes"
#define D_CMND_ENERGY_RESOLUTION "EnergyRes"
#define D_CMND_MODULE "Module"
#define D_CMND_MODULES "Modules"
#define D_CMND_GPIO "GPIO"
  #define D_NOT_SUPPORTED "Not supported"
#define D_CMND_GPIOS "GPIOs"
#define D_CMND_PWM "PWM"
#define D_CMND_PWMFREQUENCY "PWMFrequency"
#define D_CMND_PWMRANGE "PWMRange"
#define D_CMND_COUNTER "Counter"
#define D_CMND_COUNTERTYPE "CounterType"
#define D_CMND_COUNTERDEBOUNCE "CounterDebounce"
#define D_CMND_SLEEP "Sleep"
#define D_CMND_UPLOAD "Upload"
#define D_CMND_UPGRADE "Upgrade"
  #define D_ONE_OR_GT "1 or >%s to upgrade"
#define D_CMND_OTAURL "OtaUrl"
#define D_CMND_SERIALLOG "SerialLog"
#define D_CMND_SYSLOG "SysLog"
#define D_CMND_LOGHOST "LogHost"
#define D_CMND_LOGPORT "LogPort"
#define D_CMND_IPADDRESS "IPAddress"
#define D_CMND_NTPSERVER "NtpServer"
#define D_CMND_AP "Ap"
#define D_CMND_SSID "SSId"
#define D_CMND_PASSWORD "Password"
#define D_CMND_HOSTNAME "Hostname"
#define D_CMND_WIFICONFIG "WifiConfig"
  #define WCFG_MAX_STRING_LENGTH 12
  #define D_WCFG_0_RESTART "Restart"
  #define D_WCFG_1_SMARTCONFIG "SmartConfig"
  #define D_WCFG_2_WIFIMANAGER "WifiManager"
  #define D_WCFG_3_WPSCONFIG "WPSConfig"
  #define D_WCFG_4_RETRY "Retry"
  #define D_WCFG_5_WAIT "Wait"
#define D_CMND_FRIENDLYNAME "FriendlyName"
#define D_CMND_SWITCHMODE "SwitchMode"
#define D_CMND_WEBSERVER "Webserver"
  #define D_WEBSERVER_MODE "WebServerMode"
  #define D_ACTIVE_FOR "Active for"
  #define D_ON_DEVICE "on"
#define D_CMND_WEBPASSWORD "WebPassword"
#define D_CMND_WEBLOG "WebLog"
#define D_CMND_EMULATION "Emulation"
#define D_CMND_TELEPERIOD "TelePeriod"
#define D_CMND_RESTART "Restart"
  #define D_ONE_TO_RESTART "1 to restart"
#define D_CMND_RESET "Reset"
  #define D_RESET_AND_RESTARTING "Reset and Restarting"
  #define D_ONE_TO_RESET "1 to reset"
#define D_CMND_TIMEZONE "Timezone"
#define D_CMND_ALTITUDE "Altitude"
#define D_CMND_LEDPOWER "LedPower"
#define D_CMND_LEDSTATE "LedState"
#define D_CMND_CFGDUMP "CfgDump"
#define D_CMND_I2CSCAN "I2CScan"
#define D_CMND_OUT "CmndOUT" // add cpat
#define D_CMND_EXCEPTION "Exception"

// Commands xdrv_domoticz.ino
#define D_CMND_DOMOTICZ "Domoticz"
#define D_CMND_IDX "Idx"
#define D_CMND_KEYIDX "KeyIdx"
#define D_CMND_SWITCHIDX "SwitchIdx"
#define D_CMND_SENSORIDX "SensorIdx"
#define D_CMND_UPDATETIMER "UpdateTimer"

// Commands xdrv_ir_send.ino
#define D_CMND_IRSEND "IRSend"
#define D_CMND_IRHVAC "IRHVAC"

// Commands xdrv_snfbridge.ino
#define D_CMND_RFCODE "RfCode"
#define D_CMND_RFHIGH "RfHigh"
#define D_CMND_RFHOST "RfHost"
#define D_CMND_RFKEY "RfKey"
#define D_CMND_RFLOW "RfLow"
#define D_CMND_RFSYNC "RfSync"

// Commands xdrv_snfled.ino
#define D_CMND_COLOR "Color"
#define D_CMND_COLORTEMPERATURE "CT"
#define D_CMND_DIMMER "Dimmer"
#define D_CMND_LED "Led"
#define D_CMND_LEDTABLE "LedTable"
#define D_CMND_FADE "Fade"
#define D_CMND_PIXELS "Pixels"
#define D_CMND_SCHEME "Scheme"
#define D_CMND_SPEED "Speed"
#define D_CMND_WAKEUP "Wakeup"
#define D_CMND_WAKEUPDURATION "WakeUpDuration"
#define D_CMND_WIDTH "Width"

// Commands xsns_hlw8012.ino
#ifdef Use_HLW8012
	#define D_CMND_POWERLOW "PowerLow"
	#define D_CMND_POWERHIGH "PowerHigh"
	#define D_CMND_VOLTAGELOW "VoltageLow"
	#define D_CMND_VOLTAGEHIGH "VoltageHigh"
	#define D_CMND_CURRENTLOW "CurrentLow"
	#define D_CMND_CURRENTHIGH "CurrentHigh"
	#define D_CMND_ENERGYRESET "EnergyReset"
	#define D_CMND_HLWPCAL "HlwPcal"
	#define D_CMND_HLWPSET "HlwPset"
	#define D_CMND_HLWUCAL "HlwUcal"
	#define D_CMND_HLWUSET "HlwUset"
	#define D_CMND_HLWICAL "HlwIcal"
	#define D_CMND_HLWISET "HlwIset"
	#define D_CMND_MAXPOWER "MaxPower"
	#define D_CMND_MAXPOWERHOLD "MaxPowerHold"
	#define D_CMND_MAXPOWERWINDOW "MaxPowerWindow"
	#define D_CMND_SAFEPOWER "SafePower"
	#define D_CMND_SAFEPOWERHOLD "SafePowerHold"
	#define D_CMND_SAFEPOWERWINDOW "SafePowerWindow"
	#define D_CMND_MAXENERGY "MaxEnergy"
	#define D_CMND_MAXENERGYSTART "MaxEnergyStart"
#endif
#endif  // _LANGUAGE_FR_FR_H_
